import { EquiposDataType } from './functions/interfaces';

export const equiposData: EquiposDataType = {
    'Real Betis' : {
        'id'        : 1,
        'escudo'    : 'escudo-betis.png',
        'escudo-gris' : 'escudo-betis.png',
        'defensa'   : 60,
        'medio'     : 60,
        'ataque'    : 50,
        'dureza'    : 40,
        'velocidad' : 60,
        'disparo'   : 50,
        'punteria'  : 70,
    },
    'Sevilla' : {
        'id'        : 1,
        'escudo'    : 'escudo-sevilla.png',
        'escudo-gris' : 'escudo-sevilla.png',
        'defensa'   : 60,
        'medio'     : 60,
        'ataque'    : 50,
        'dureza'    : 40,
        'velocidad' : 60,
        'disparo'   : 50,
        'punteria'  : 70,
    },
    'FC.Barcelona' : {
        'id'        : 1,
        'escudo'    : 'escudo-barcelona.png',
        'escudo-gris' : 'escudo-barcelona.png',
        'defensa'   : 60,
        'medio'     : 60,
        'ataque'    : 50,
        'dureza'    : 40,
        'velocidad' : 60,
        'disparo'   : 50,
        'punteria'  : 70,
    },
    'Real Madrid' : {
        'id'        : 1,
        'escudo'    : 'escudo-madrid.png',
        'escudo-gris' : 'escudo-madrid.png',
        'defensa'   : 60,
        'medio'     : 60,
        'ataque'    : 50,
        'dureza'    : 40,
        'velocidad' : 60,
        'disparo'   : 50,
        'punteria'  : 70,
    },

}